### ISSUE TITLE
Support *.web.db.svc.eqiad.wmflabs and *.analytics.db.svc.eqiad.wmflabs Wiki Replica service names

### ISSUE THREAD

**Issue by bd808** [legoktm/toolforge#1]
As [announced by the WMCS team](https://phabricator.wikimedia.org/phame/post/view/70/new_wiki_replica_servers_ready_for_use/), there are new service names for access Wiki Replica servers which allow users to indicate if they need results quickly (`*.web`) or if they are doing something that can take longer to return but also use more database server resources (`*.analytics`).

It would be nice if this choice was exposed in the toolforge library. One possible way to do this would be to add a new keyword argument to `toolforge.connect()` that defaulted  to one or the other option for backwards compatibility.

Bonus points for adding a way to also use `toolforge.connect()` or another helper function (`toolsdb()`?) to connect to the `tools.db.svc.eqiad.wmflabs` host where user managed tables are allowed.

**Comment by legoktm** [comment]
OK, I can implement that. Any recommendations on whether web or analytics should be the default?

**Comment by bd808** [comment]
@legoktm which ever you personally expect to use more? In the long term the expected trade off is response time. Web will try to remain responsive at the expense of stricter query duration limits. Analytics will bias in the other direction with responses to individual queries disadvantaged in favor of letting everyone's queries run longer before being killed.

**Comment by legoktm** [comment]
I split the bonus request to #4.
