### ISSUE TITLE
Python 2.7 package on toolforge

### ISSUE THREAD

**Issue by Nudin** [legoktm/toolforge#12]
On toolforge there is a globally installed `toolforge` in the folder `/usr/lib/python2.7/dist-packages/toolforge`. This has a different structure than the code here has. Is this an old version that should be removed? Or is this something else with a collision of names?

**Comment by legoktm** [comment]
Looks like an accidental collision - I've opened https://phabricator.wikimedia.org/T249079 to track it

**Comment by legoktm** [comment]
This has been fixed by renaming the other package.
