### ISSUE TITLE
Calling set_user_agent more than once leads to appending user agents unexpectedly

### ISSUE THREAD

**Issue by Retailed** [legoktm/toolforge#14]
## Description

As I understand, current `set_user_agent` implementation relies on modifying `default_user_agent` from *requests*. The problem arises, when `set_user_agent` is called more then once on a single run. Expected behaviour for any *set*-type function is to save new values, but current implementation updates the old value with a new data, not rewrites it.

As there is a header size limitations, multiple use of `set_user_agent` can lead to hard-to-detect errors.

## Example
```python
import toolforge

for i in range(2):
    print(toolforge.set_user_agent("test"))
```

Example output:
```python
test (https://test.toolforge.org/; tools.test@tools.wmflabs.org) python-requests/2.25.1
test (https://test.toolforge.org/; tools.test@tools.wmflabs.org) test (https://test.toolforge.org/; tools.test@tools.wmflabs.org) python-requests/2.25.1
```

Expected output:
```python
test (https://test.toolforge.org/; tools.test@tools.wmflabs.org) python-requests/2.25.1
test (https://test.toolforge.org/; tools.test@tools.wmflabs.org) python-requests/2.25.1
```

**Comment by legoktm** [comment]
Yeah, `set_user_agent` is supposed to be called only once. Is there a reason you want to call it multiple times?

**Comment by Retailed** [comment]
> Yeah, `set_user_agent` is supposed to be called only once. Is there a reason you want to call it multiple times?

I use multiple `mwapi` sessions, because I need to access different wikis. I called `set_user_agent` right before creating each session.

Of course, I can set user agent once and pass it deep down till the request is made, but if there's a more logical and convenient way to access this value, please notify.

**Comment by legoktm** [comment]
I pushed a fix to master, I'll aim to do a release later today (need to fix CI first).

**Comment by legoktm** [comment]
@Retailed you should be able to use `toolforge>=4.4.0` in your projects now.
