### ISSUE TITLE
Add a toolforge.on_toolforge() helper

### ISSUE THREAD

**Issue by legoktm** [legoktm/toolforge#6]
Goal would be to differentiate whether we're running in cloud services/toolforge or on someone's laptop.

Related: https://phabricator.wikimedia.org/T192244 (which would make this easier)

**Comment by framawiki** [comment]
See https://gerrit.wikimedia.org/r/#/c/394998/5/pywikibot/version.py

**Comment by bd808** [comment]
Imported to Phabricator as https://phabricator.wikimedia.org/T333726
