### ISSUE TITLE
Disable redirect_to_https

### ISSUE THREAD

**Issue by lucaswerkmeister** [legoktm/toolforge#8]
Since [all of Toolforge now redirects to HTTPS](https://phabricator.wikimedia.org/phame/post/view/132/migrating_tools.wmflabs.org_to_https/) ([T102367](https://phabricator.wikimedia.org/T102367)), the `toolforge.redirect_to_https` handler is no longer necessary as far as I can tell. Of course, it should still be retained for compatibility, but I think its body can now be replaced with a simple `pass` and its documentation can indicate that it’s now unnecessary.

**Comment by legoktm** [comment]
Thanks for the reminder, fixed and included in the 4.2.0 release.

**Comment by lucaswerkmeister** [comment]
Great, thanks!
